CREATE TABLE [Silver].[Claim] (
    [claim_sk]                    VARCHAR (64)   NULL,
    [claim_id]                    VARCHAR (8000) NULL,
    [patient_id]                  VARCHAR (8000) NULL,
    [provider_id]                 VARCHAR (8000) NULL,
    [provider_display]            VARCHAR (8000) NULL,
    [provider_identifier_system]  VARCHAR (8000) NULL,
    [provider_identifier_value]   VARCHAR (8000) NULL,
    [insurer_org_id]              VARCHAR (8000) NULL,
    [insurer_display]             VARCHAR (8000) NULL,
    [facility_id]                 VARCHAR (8000) NULL,
    [facility_display]            VARCHAR (8000) NULL,
    [coverage_id]                 VARCHAR (8000) NULL,
    [coverage_display]            VARCHAR (8000) NULL,
    [insurance_focal]             BIT            NULL,
    [insurance_sequence]          BIGINT         NULL,
    [insurance_identifier_system] VARCHAR (8000) NULL,
    [insurance_identifier_value]  VARCHAR (8000) NULL,
    [prescription_reference]      VARCHAR (8000) NULL,
    [claim_status]                VARCHAR (8000) NULL,
    [claim_use]                   VARCHAR (8000) NULL,
    [type_code]                   VARCHAR (8000) NULL,
    [type_display]                VARCHAR (8000) NULL,
    [type_text]                   VARCHAR (8000) NULL,
    [subtype_code]                VARCHAR (8000) NULL,
    [subtype_text]                VARCHAR (8000) NULL,
    [priority_code]               VARCHAR (8000) NULL,
    [priority_display]            VARCHAR (8000) NULL,
    [payee_type_code]             VARCHAR (8000) NULL,
    [claim_created_date]          DATETIME2 (0)  NULL,
    [billable_period_start]       DATETIME2 (0)  NULL,
    [billable_period_end]         DATETIME2 (0)  NULL,
    [total_amount]                FLOAT (53)     NULL,
    [total_currency]              VARCHAR (8000) NULL,
    [identifier_system]           VARCHAR (8000) NULL,
    [identifier_value]            VARCHAR (8000) NULL,
    [is_latest]                   INT            NOT NULL,
    [version_rank]                BIGINT         NULL,
    [meta_lastupdated]            DATETIME2 (0)  NULL,
    [meta_source]                 VARCHAR (8000) NULL,
    [meta_versionid]              VARCHAR (8000) NULL,
    [resource_type]               VARCHAR (8000) NULL,
    [search_mode]                 VARCHAR (8000) NULL,
    [full_url]                    VARCHAR (8000) NULL,
    [silver_loaded_at]            DATETIME2 (0)  NULL
);


GO