CREATE TABLE [Silver].[Coverage] (
    [coverage_sk]             VARCHAR (64)   NULL,
    [coverage_id]             VARCHAR (8000) NULL,
    [patient_id]              VARCHAR (8000) NULL,
    [beneficiary_display]     VARCHAR (8000) NULL,
    [subscriber_id]           VARCHAR (8000) NULL,
    [subscriber_display]      VARCHAR (8000) NULL,
    [subscriber_member_id]    VARCHAR (8000) NULL,
    [payor_org_id]            VARCHAR (8000) NULL,
    [payor_display]           VARCHAR (8000) NULL,
    [payor_identifier_system] VARCHAR (8000) NULL,
    [payor_identifier_value]  VARCHAR (8000) NULL,
    [coverage_status]         VARCHAR (8000) NULL,
    [coverage_order]          BIGINT         NULL,
    [network]                 VARCHAR (8000) NULL,
    [type_code]               VARCHAR (8000) NULL,
    [type_display]            VARCHAR (8000) NULL,
    [type_system]             VARCHAR (8000) NULL,
    [type_text]               VARCHAR (8000) NULL,
    [class_type_code]         VARCHAR (8000) NULL,
    [class_type_display]      VARCHAR (8000) NULL,
    [class_value]             VARCHAR (8000) NULL,
    [class_name]              VARCHAR (8000) NULL,
    [relationship_code]       VARCHAR (8000) NULL,
    [relationship_display]    VARCHAR (8000) NULL,
    [period_start]            VARCHAR (8000) NULL,
    [period_end]              VARCHAR (8000) NULL,
    [identifier_system]       VARCHAR (8000) NULL,
    [identifier_value]        VARCHAR (8000) NULL,
    [identifier_type_code]    VARCHAR (8000) NULL,
    [identifier_type_text]    VARCHAR (8000) NULL,
    [effective_start_date]    DATETIME2 (0)  NULL,
    [effective_end_date]      DATETIME2 (0)  NULL,
    [is_current]              INT            NOT NULL,
    [meta_lastupdated]        DATETIME2 (0)  NULL,
    [meta_source]             VARCHAR (8000) NULL,
    [meta_versionid]          VARCHAR (8000) NULL,
    [meta_profile]            VARCHAR (8000) NULL,
    [resource_type]           VARCHAR (8000) NULL,
    [search_mode]             VARCHAR (8000) NULL,
    [full_url]                VARCHAR (8000) NULL,
    [Silver_loaded_at]        DATETIME2 (0)  NULL
);


GO