CREATE TABLE [Silver].[Organization] (
    [org_sk]                  VARCHAR (64)   NULL,
    [org_id]                  VARCHAR (8000) NULL,
    [org_name]                VARCHAR (8000) NULL,
    [org_alias]               VARCHAR (8000) NULL,
    [is_active]               BIT            NULL,
    [language]                VARCHAR (8000) NULL,
    [type_code]               VARCHAR (8000) NULL,
    [type_display]            VARCHAR (8000) NULL,
    [type_system]             VARCHAR (8000) NULL,
    [type_text]               VARCHAR (8000) NULL,
    [address_use]             VARCHAR (8000) NULL,
    [address_type]            VARCHAR (8000) NULL,
    [address_text]            VARCHAR (8000) NULL,
    [address_line]            VARCHAR (8000) NULL,
    [address_city]            VARCHAR (8000) NULL,
    [address_district]        VARCHAR (8000) NULL,
    [address_state]           VARCHAR (8000) NULL,
    [address_postalcode]      VARCHAR (8000) NULL,
    [address_country]         VARCHAR (8000) NULL,
    [telecom_system]          VARCHAR (8000) NULL,
    [telecom_use]             VARCHAR (8000) NULL,
    [telecom_value]           VARCHAR (8000) NULL,
    [telecom_rank]            BIGINT         NULL,
    [contact_name_text]       VARCHAR (8000) NULL,
    [contact_name_given]      VARCHAR (8000) NULL,
    [contact_name_family]     VARCHAR (8000) NULL,
    [contact_purpose_code]    VARCHAR (8000) NULL,
    [contact_purpose_display] VARCHAR (8000) NULL,
    [contact_telecom_value]   VARCHAR (8000) NULL,
    [identifier_system]       VARCHAR (8000) NULL,
    [identifier_value]        VARCHAR (8000) NULL,
    [identifier_type_code]    VARCHAR (8000) NULL,
    [identifier_type_display] VARCHAR (8000) NULL,
    [parent_org_id]           VARCHAR (8000) NULL,
    [parent_org_display]      VARCHAR (8000) NULL,
    [effective_start_date]    DATETIME2 (0)  NULL,
    [effective_end_date]      DATETIME2 (0)  NULL,
    [is_current]              INT            NOT NULL,
    [meta_lastupdated]        DATETIME2 (0)  NULL,
    [meta_source]             VARCHAR (8000) NULL,
    [meta_versionid]          VARCHAR (8000) NULL,
    [meta_profile]            VARCHAR (8000) NULL,
    [resource_type]           VARCHAR (8000) NULL,
    [search_mode]             VARCHAR (8000) NULL,
    [full_url]                VARCHAR (8000) NULL,
    [Silver_loaded_at]        DATETIME2 (0)  NULL
);


GO