{{
    config(
        materialized = 'table',
        schema       = 'Silver'
    )
}}

SELECT [coverage_sk],
			[coverage_id],
			[patient_id],
			[beneficiary_display],
			[subscriber_id],
			[subscriber_display],
			[subscriber_member_id],
			[payor_org_id],
			[payor_display],
			[payor_identifier_system],
			[payor_identifier_value],
			[coverage_status],
			[coverage_order],
			[network],
			[type_code],
			[type_display],
			[type_system],
			[type_text],
			[class_type_code],
			[class_type_display],
			[class_value],
			[class_name],
			[relationship_code],
			[relationship_display],
			[period_start],
			[period_end],
			[identifier_system],
			[identifier_value],
			[identifier_type_code],
			[identifier_type_text],
			{{ to_datetime2('effective_start_date' )}} AS effective_start_date,
			{{ to_datetime2('effective_end_date' )}} AS effective_end_date,
			[is_current],
			{{ to_datetime2('meta_lastupdated' )}} AS meta_lastupdated,
			[meta_source],
			[meta_versionid],
			[meta_profile],
			[resource_type],
			[search_mode],
			[full_url],
			{{ to_datetime2('Silver_loaded_at' )}} AS Silver_loaded_at
FROM {{ source('Silver', 'dim_coverage') }} where [is_current] = 1 and [patient_id] IS NOT NULL