{{
    config(
        materialized = 'table',
        schema       = 'Silver'
    )
}}

SELECT [org_sk],
			[org_id],
			[org_name],
			[org_alias],
			[is_active],
			[language],
			[type_code],
			[type_display],
			[type_system],
			[type_text],
			[address_use],
			[address_type],
			[address_text],
			[address_line],
			[address_city],
			[address_district],
			[address_state],
			[address_postalcode],
			[address_country],
			[telecom_system],
			[telecom_use],
			[telecom_value],
			[telecom_rank],
			[contact_name_text],
			[contact_name_given],
			[contact_name_family],
			[contact_purpose_code],
			[contact_purpose_display],
			[contact_telecom_value],
			[identifier_system],
			[identifier_value],
			[identifier_type_code],
			[identifier_type_display],
			[parent_org_id],
			[parent_org_display],
			{{ to_datetime2('effective_start_date' )}} AS [effective_start_date],
			{{ to_datetime2('effective_end_date' )}} AS [effective_end_date],
			[is_current],
			{{ to_datetime2('meta_lastupdated' )}} AS [meta_lastupdated],
			[meta_source],
			[meta_versionid],
			[meta_profile],
			[resource_type],
			[search_mode],
			[full_url],
			{{ to_datetime2('Silver_loaded_at' )}} AS [Silver_loaded_at]
FROM {{ source('Silver', 'dim_organization') }} where [is_current] = 1