CREATE TABLE [Gold].[ClaimSummary] (
    [claim_sk]            VARCHAR (64)   NULL,
    [claim_id]            VARCHAR (8000) NULL,
    [claim_status]        VARCHAR (8000) NULL,
    [claim_use]           VARCHAR (8000) NULL,
    [claim_type]          VARCHAR (8000) NULL,
    [claim_subtype]       VARCHAR (8000) NULL,
    [claim_priority]      VARCHAR (8000) NULL,
    [patient_id]          VARCHAR (8000) NULL,
    [patient_name]        VARCHAR (8000) NULL,
    [patient_gender]      VARCHAR (8000) NULL,
    [patient_dob]         VARCHAR (8000) NULL,
    [patient_city]        VARCHAR (8000) NULL,
    [patient_state]       VARCHAR (8000) NULL,
    [provider_id]         VARCHAR (8000) NULL,
    [provider_name]       VARCHAR (8000) NULL,
    [insurer_org_id]      VARCHAR (8000) NULL,
    [insurer_name]        VARCHAR (8000) NULL,
    [insurer_city]        VARCHAR (8000) NULL,
    [facility_id]         VARCHAR (8000) NULL,
    [facility_name]       VARCHAR (8000) NULL,
    [coverage_id]         VARCHAR (8000) NULL,
    [coverage_type]       VARCHAR (8000) NULL,
    [insurance_network]   VARCHAR (8000) NULL,
    [plan_class]          VARCHAR (8000) NULL,
    [payor_display]       VARCHAR (8000) NULL,
    [claim_created_date]  DATE           NULL,
    [service_start_date]  DATE           NULL,
    [service_end_date]    DATE           NULL,
    [service_days]        INT            NULL,
    [claimed_total]       FLOAT (53)     NULL,
    [total_currency]      VARCHAR (8000) NULL,
    [items_net_total]     FLOAT (53)     NOT NULL,
    [line_item_count]     INT            NOT NULL,
    [total_units_claimed] FLOAT (53)     NOT NULL,
    [distinct_services]   INT            NOT NULL,
    [diagnosis_count]     INT            NOT NULL,
    [procedure_count]     INT            NOT NULL,
    [care_team_size]      INT            NOT NULL,
    [version_rank]        BIGINT         NULL,
    [claim_last_updated]  DATETIME2 (0)  NULL,
    [gold_loaded_at]      DATETIME2 (0)  NULL
);


GO