CREATE TABLE [Gold].[InvoiceReconciliation] (
    [invoice_sk]              VARCHAR (64)   NULL,
    [invoice_id]              VARCHAR (8000) NULL,
    [invoice_status]          VARCHAR (8000) NULL,
    [invoice_date]            DATE           NULL,
    [claim_id]                VARCHAR (8000) NULL,
    [claim_type]              VARCHAR (8000) NULL,
    [claim_status]            VARCHAR (8000) NULL,
    [service_start_date]      DATE           NULL,
    [service_end_date]        DATE           NULL,
    [claimed_amount]          FLOAT (53)     NULL,
    [currency]                VARCHAR (8000) NULL,
    [patient_id]              VARCHAR (8000) NULL,
    [patient_name]            VARCHAR (8000) NULL,
    [patient_gender]          VARCHAR (8000) NULL,
    [address_city]            VARCHAR (8000) NULL,
    [address_state]           VARCHAR (8000) NULL,
    [issuer_display]          VARCHAR (8000) NULL,
    [issuer_identifier_value] VARCHAR (8000) NULL,
    [issuer_org_name]         VARCHAR (8000) NULL,
    [total_gross_amount]      FLOAT (53)     NULL,
    [total_gross_currency]    VARCHAR (8000) NULL,
    [total_net_amount]        FLOAT (53)     NULL,
    [total_net_currency]      VARCHAR (8000) NULL,
    [base_charge]             FLOAT (53)     NOT NULL,
    [tax_amount]              FLOAT (53)     NOT NULL,
    [discount_amount]         FLOAT (53)     NOT NULL,
    [deduction_amount]        FLOAT (53)     NOT NULL,
    [surcharge_amount]        FLOAT (53)     NOT NULL,
    [informational_amount]    FLOAT (53)     NOT NULL,
    [invoice_line_count]      INT            NOT NULL,
    [gross_variance]          FLOAT (53)     NULL,
    [net_variance]            FLOAT (53)     NULL,
    [net_to_claimed_pct]      FLOAT (53)     NULL,
    [note_text]               VARCHAR (8000) NULL,
    [invoice_last_updated]    DATETIME2 (0)  NULL,
    [gold_loaded_at]          DATETIME2 (0)  NULL
);


GO