CREATE TABLE [Gold].[Patient360] (
    [patient_id]           VARCHAR (8000) NULL,
    [full_name]            VARCHAR (8000) NOT NULL,
    [name_family]          VARCHAR (8000) NULL,
    [name_given]           VARCHAR (8000) NULL,
    [gender]               VARCHAR (8000) NULL,
    [birth_date]           VARCHAR (8000) NULL,
    [age_years]            INT            NULL,
    [address_line]         VARCHAR (8000) NULL,
    [address_city]         VARCHAR (8000) NULL,
    [address_state]        VARCHAR (8000) NULL,
    [address_postalcode]   VARCHAR (8000) NULL,
    [phone_or_email]       VARCHAR (8000) NULL,
    [coverage_id]          VARCHAR (8000) NULL,
    [coverage_type]        VARCHAR (8000) NULL,
    [coverage_class]       VARCHAR (8000) NULL,
    [insurance_network]    VARCHAR (8000) NULL,
    [coverage_start]       VARCHAR (8000) NULL,
    [coverage_end]         VARCHAR (8000) NULL,
    [member_relationship]  VARCHAR (8000) NULL,
    [subscriber_member_id] VARCHAR (8000) NULL,
    [payor_display]        VARCHAR (8000) NULL,
    [payor_org_name]       VARCHAR (8000) NULL,
    [total_claims]         INT            NOT NULL,
    [total_claimed_amount] FLOAT (53)     NOT NULL,
    [first_claim_date]     DATE           NULL,
    [last_claim_date]      DATE           NULL,
    [active_claims]        INT            NOT NULL,
    [cancelled_claims]     INT            NOT NULL,
    [total_invoices]       INT            NOT NULL,
    [total_gross_billed]   FLOAT (53)     NOT NULL,
    [total_net_billed]     FLOAT (53)     NOT NULL,
    [total_discounts]      FLOAT (53)     NOT NULL,
    [last_invoice_date]    DATE           NULL,
    [net_to_gross_pct]     FLOAT (53)     NULL,
    [patient_last_updated] DATETIME2 (0)  NULL,
    [gold_loaded_at]       DATETIME2 (0)  NULL
);


GO